import threading
from django.http import HttpResponse
from rest_framework.request import Request
from _typeshed import Incomplete

logger: Incomplete

def SetupPrometheusEndpointOnPort(port: Incomplete, addr: str = ...) -> None: ...

class PrometheusEndpointServer(threading.Thread):
    httpd: Incomplete
    def __init__(self, httpd: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def run(self) -> None: ...

def SetupPrometheusEndpointOnPortRange(port_range: Incomplete, addr: str = ...) -> Incomplete: ...
def SetupPrometheusExportsFromConfig() -> None: ...
def ExportToDjangoView(request: Request) -> HttpResponse: ...
