from _typeshed import Incomplete

def Time() -> Incomplete: ...
def TimeSince(t: Incomplete) -> Incomplete: ...
def PowersOf(logbase: Incomplete, count: Incomplete, lower: int = ..., include_zero: bool = ...) -> Incomplete: ...
