# Generated by Django 6.0 on 2025-12-26 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "actor_object_id",
                    models.PositiveIntegerField(
                        help_text="The object ID of the actor.", verbose_name="actor object ID"
                    ),
                ),
                ("verb", models.CharField(help_text="The action performed.", max_length=255, verbose_name="verb")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the notification.", verbose_name="description"
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="The object ID of the target.", null=True, verbose_name="target object ID"
                    ),
                ),
                (
                    "unread",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether the notification is unread.",
                        verbose_name="unread",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("success", "Success"), ("warning", "Warning"), ("error", "Error")],
                        default="info",
                        help_text="The level of the notification.",
                        max_length=20,
                        verbose_name="level",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time the notification was created.", verbose_name="timestamp"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, help_text="Optional JSON data for the notification.", null=True, verbose_name="data"
                    ),
                ),
                (
                    "actor_content_type",
                    models.ForeignKey(
                        help_text="The content type of the actor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_actor",
                        to="contenttypes.contenttype",
                        verbose_name="actor content type",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who will receive the notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The content type of the target.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_target",
                        to="contenttypes.contenttype",
                        verbose_name="target content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ("-timestamp",),
                "indexes": [models.Index(fields=["recipient", "unread"], name="notification_recip_unread_idx")],
            },
        ),
    ]
