# Generated by Django 6.0.2 on 2026-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[("system", "System"), ("friendship", "Friendship"), ("game_release", "Game Release")],
                default="system",
                help_text="The category of the notification.",
                max_length=20,
                verbose_name="category",
            ),
        ),
    ]
