from _typeshed import Incomplete
from docker import utils as utils
from docker.constants import DEFAULT_UNIX_SOCKET as DEFAULT_UNIX_SOCKET, IS_WINDOWS_PLATFORM as IS_WINDOWS_PLATFORM
from docker.utils.config import find_config_file as find_config_file

METAFILE: str

def get_current_context_name() -> Incomplete: ...
def write_context_name_to_docker_config(name: Incomplete | None = ...) -> Incomplete: ...
def get_context_id(name: Incomplete) -> Incomplete: ...
def get_context_dir() -> Incomplete: ...
def get_meta_dir(name: Incomplete | None = ...) -> Incomplete: ...
def get_meta_file(name: Incomplete) -> Incomplete: ...
def get_tls_dir(name: Incomplete | None = ..., endpoint: str = ...) -> Incomplete: ...
def get_context_host(path: Incomplete | None = ..., tls: bool = ...) -> Incomplete: ...
