[tox]
toxworkdir = /tmp/.tox
envlist =
    py3
    ruff
    black
    mypy
    django_project

[testenv]
runner = uv-venv-lock-runner
description = start the postgres database and run tests with coverage
usedevelop = true
basepython = python3.14
passenv =
    CI*
    DJANGO*
    MYGAMELIST*
    DOCKER_HOST
extras =
    test
    cov
commands =
    pytest --cov=my_game_list --cov-report=xml:coverage-reports/coverage.xml --cov-report=term --color=yes -n auto tests {posargs}

[testenv:ruff]
runner = uv-venv-lock-runner
description = run linter via ruff
commands =
    uv run ruff check .

[testenv:black]
runner = uv-venv-lock-runner
description = run formatter via black
commands =
    uv run black --check .

[testenv:mypy]
runner = uv-venv-lock-runner
description = run type checker via mypy
commands =
    uv run mypy --strict .

[testenv:django_project]
runner = uv-venv-lock-runner
description = run django check command
allowlist_externals = {toxinidir}/scripts/my-game-list-manage.py
commands =
    {toxinidir}/scripts/my-game-list-manage.py check
