from ..errors import DockerException as DockerException
from _typeshed import Incomplete

class CancellableStream:
    def __init__(self, stream: Incomplete, response: Incomplete) -> None: ...
    def __iter__(self) -> Incomplete: ...
    def __next__(self) -> Incomplete: ...
    next = __next__
    def close(self) -> None: ...
