from .base import DictType as DictType
from _typeshed import Incomplete

class Healthcheck(DictType):
    def __init__(self, **kwargs: Incomplete) -> None: ...
    @property
    def test(self) -> Incomplete: ...
    @property
    def interval(self) -> Incomplete: ...
    @property
    def timeout(self) -> Incomplete: ...
    @property
    def retries(self) -> Incomplete: ...
    @property
    def start_period(self) -> Incomplete: ...
