import reprlib as reprlib_module
from _typeshed import Incomplete

builtin_repr = repr

class SafeRepr(reprlib_module.Repr):
    def repr(self, x: Incomplete) -> Incomplete: ...
    def repr_unicode(self, x: Incomplete, level: Incomplete) -> Incomplete: ...
    def repr_instance(self, x: Incomplete, level: Incomplete) -> Incomplete: ...

def saferepr(obj: Incomplete, maxsize: int = ...) -> Incomplete: ...
