from typing import Callable
from _typeshed import Incomplete
from datetime import datetime

def make_utc(dt: datetime) -> datetime: ...
def aware_utcnow() -> datetime: ...
def datetime_to_epoch(dt: datetime) -> datetime: ...
def datetime_from_epoch(ts: float) -> datetime: ...
def format_lazy(s: str, *args: Incomplete, **kwargs: Incomplete) -> str: ...

format_lazy: Callable[[Incomplete], str]  #  type: ignore[no-redef]
