import logging
from datetime import datetime
from typing import Any

def get_md5_hash_password(password: str) -> str: ...
def make_utc(dt: datetime) -> datetime: ...
def aware_utcnow() -> datetime: ...
def datetime_to_epoch(dt: datetime) -> int: ...
def datetime_from_epoch(ts: float) -> datetime: ...
def format_lazy(s: str, *args: Any, **kwargs: Any) -> str: ...

logger: logging.Logger
