# Generated by Django 5.1.1 on 2024-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="igdb_id",
            field=models.PositiveIntegerField(unique=True, verbose_name="igdb id"),
        ),
    ]
