# Generated by Django 5.1.1 on 2024-09-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_developer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Developer",
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
