# Generated by Django 5.1.1 on 2024-12-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_company_igdb_checksum_game_igdb_checksum_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="igdb_checksum",
        ),
        migrations.RemoveField(
            model_name="game",
            name="igdb_checksum",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="igdb_checksum",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="igdb_checksum",
        ),
    ]
