# Generated by Django 5.2.8 on 2025-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_alter_gamefollow_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="igdb_updated_at",
            field=models.DateTimeField(default="1998-01-01", verbose_name="igdb last updated at"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="igdb_updated_at",
            field=models.DateTimeField(default="1998-01-01", verbose_name="igdb last updated at"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genre",
            name="igdb_updated_at",
            field=models.DateTimeField(default="1998-01-01", verbose_name="igdb last updated at"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="igdb_updated_at",
            field=models.DateTimeField(default="1998-01-01", verbose_name="igdb last updated at"),
            preserve_default=False,
        ),
    ]
