# Generated by Django 5.2.8 on 2025-12-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_company_igdb_updated_at_game_igdb_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
