# Generated by Django 6.0 on 2025-12-31 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_alter_game_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score_sum", models.BigIntegerField(default=0, verbose_name="score sum")),
                ("score_count", models.PositiveIntegerField(default=0, verbose_name="score count")),
                (
                    "average_score",
                    models.DecimalField(
                        db_index=True, decimal_places=2, default=0, max_digits=4, verbose_name="average score"
                    ),
                ),
                ("members_count", models.PositiveIntegerField(db_index=True, default=0, verbose_name="members count")),
                ("popularity", models.PositiveIntegerField(db_index=True, null=True, verbose_name="popularity")),
                ("rank_position", models.PositiveIntegerField(db_index=True, null=True, verbose_name="rank position")),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="games.game"
                    ),
                ),
            ],
            options={
                "verbose_name": "game stats",
                "verbose_name_plural": "game stats",
            },
        ),
    ]
