# Generated by Django 6.0 on 2025-12-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_gamestats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creation time"),
        ),
    ]
