# Generated by Django 6.0 on 2026-01-01 14:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0017_alter_game_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEngine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                ("igdb_updated_at", models.DateTimeField(verbose_name="igdb last updated at")),
            ],
            options={
                "verbose_name": "game engine",
                "verbose_name_plural": "game engines",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                ("igdb_updated_at", models.DateTimeField(verbose_name="igdb last updated at")),
            ],
            options={
                "verbose_name": "game mode",
                "verbose_name_plural": "game modes",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                ("igdb_updated_at", models.DateTimeField(verbose_name="igdb last updated at")),
                ("status", models.CharField(max_length=255, unique=True, verbose_name="status")),
            ],
            options={
                "verbose_name": "game status",
                "verbose_name_plural": "game statuses",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                ("igdb_updated_at", models.DateTimeField(verbose_name="igdb last updated at")),
                ("type", models.CharField(max_length=255, unique=True, verbose_name="type")),
            ],
            options={
                "verbose_name": "game type",
                "verbose_name_plural": "game types",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerPerspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                ("igdb_updated_at", models.DateTimeField(verbose_name="igdb last updated at")),
            ],
            options={
                "verbose_name": "player perspective",
                "verbose_name_plural": "player perspectives",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="game",
            name="bundles",
            field=models.ManyToManyField(blank=True, related_name="bundled_in", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="dlcs",
            field=models.ManyToManyField(blank=True, related_name="dlc_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="expanded_games",
            field=models.ManyToManyField(blank=True, related_name="expanded_by", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="expansions",
            field=models.ManyToManyField(blank=True, related_name="expansion_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="forks",
            field=models.ManyToManyField(blank=True, related_name="fork_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="parent_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_games",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="ports",
            field=models.ManyToManyField(blank=True, related_name="port_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="screenshots",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="standalone_expansions",
            field=models.ManyToManyField(blank=True, related_name="standalone_expansion_of", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="game_engines",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.gameengine"),
        ),
        migrations.AddField(
            model_name="game",
            name="game_modes",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.gamemode"),
        ),
        migrations.AddField(
            model_name="game",
            name="game_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.gamestatus",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.gametype",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_perspectives",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.playerperspective"),
        ),
    ]
