# Generated by Django 6.0 on 2026-01-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_gameengine_gamemode_gamestatus_gametype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameengine",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
