# Generated by Django 6.0.2 on 2026-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0019_alter_gameengine_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="completed_at",
            field=models.DateField(blank=True, null=True, verbose_name="completed at"),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="playtime",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="playtime"),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="started_at",
            field=models.DateField(blank=True, null=True, verbose_name="started at"),
        ),
    ]
