# Generated by Django 6.0.2 on 2026-03-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0020_gamelist_completed_at_gamelist_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamelist",
            name="is_favorite",
        ),
    ]
