# Generated by Django 6.0.3 on 2026-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0021_remove_gamelist_is_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalGameSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                ("igdb_updated_at", models.DateTimeField(verbose_name="igdb last updated at")),
            ],
            options={
                "verbose_name": "external game source",
                "verbose_name_plural": "external game sources",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="game",
            name="external_game_sources",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.externalgamesource"),
        ),
    ]
