# Generated by Django 6.0.3 on 2026-04-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0022_externalgamesource_game_external_game_sources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="external_game_sources",
        ),
        migrations.CreateModel(
            name="ExternalGame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("igdb_id", models.PositiveIntegerField(unique=True, verbose_name="igdb id")),
                ("igdb_updated_at", models.DateTimeField(verbose_name="igdb last updated at")),
                ("external_id", models.CharField(max_length=255, verbose_name="external id")),
                ("url", models.URLField(max_length=500, verbose_name="url")),
                (
                    "external_game_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_games",
                        to="games.externalgamesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "external game",
                "verbose_name_plural": "external games",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="game",
            name="external_games",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.externalgame"),
        ),
    ]
