# Generated by Django 6.0.3 on 2026-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0023_remove_game_external_game_sources_externalgame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalgame",
            name="url",
            field=models.URLField(blank=True, max_length=500, verbose_name="url"),
        ),
    ]
