# Generated by Django 6.0.3 on 2026-04-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0024_alter_externalgame_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalgame",
            name="url",
            field=models.URLField(blank=True, max_length=1024, verbose_name="url"),
        ),
    ]
