# Generated by Django 6.0.3 on 2026-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_alter_externalgame_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, max_length=512, unique=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, max_length=512, unique=True, verbose_name="slug"),
        ),
    ]
