# Generated by Django 6.0.4 on 2026-05-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0026_company_slug_game_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="externalgamesource",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="externalgamesource",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="game",
            name="summary_en",
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name="summary"),
        ),
        migrations.AddField(
            model_name="game",
            name="summary_pl",
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name="summary"),
        ),
        migrations.AddField(
            model_name="game",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="game",
            name="title_pl",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="gameengine",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="gameengine",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="gamemedia",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="gamemedia",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="gamestatus",
            name="status_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="status"),
        ),
        migrations.AddField(
            model_name="gamestatus",
            name="status_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="status"),
        ),
        migrations.AddField(
            model_name="gametype",
            name="type_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="type"),
        ),
        migrations.AddField(
            model_name="gametype",
            name="type_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="type"),
        ),
        migrations.AddField(
            model_name="genre",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="genre",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="platform",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="platform",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="playerperspective",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="playerperspective",
            name="name_pl",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="name"),
        ),
    ]
