# Generated by Django 6.0.4 on 2026-05-21 07:11

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0027_company_name_en_company_name_pl_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_logo_id",
            field=models.CharField(
                blank=True,
                help_text="The IGDB logo ID used to construct the company logo image URL.",
                max_length=255,
                verbose_name="company logo id",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(help_text="The company's name.", max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name_en",
            field=models.CharField(help_text="The company's name.", max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name_pl",
            field=models.CharField(help_text="The company's name.", max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier, auto-generated from the company name.",
                max_length=512,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="externalgame",
            name="external_game_source",
            field=models.ForeignKey(
                help_text="The external platform where this game is listed (e.g. Steam, GOG).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_games",
                to="games.externalgamesource",
            ),
        ),
        migrations.AlterField(
            model_name="externalgame",
            name="external_id",
            field=models.CharField(
                help_text="The game's identifier on the external platform.", max_length=255, verbose_name="external id"
            ),
        ),
        migrations.AlterField(
            model_name="externalgame",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="externalgame",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="externalgame",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="A direct link to the game on the external platform.",
                max_length=1024,
                verbose_name="url",
            ),
        ),
        migrations.AlterField(
            model_name="externalgamesource",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="externalgamesource",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="externalgamesource",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="externalgamesource",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="externalgamesource",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="bundles",
            field=models.ManyToManyField(
                blank=True, help_text="Bundles that include this game.", related_name="bundled_in", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="cover_image_id",
            field=models.CharField(
                blank=True,
                help_text="The IGDB cover image ID used to construct the cover image URL.",
                max_length=255,
                verbose_name="cover image id",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                help_text="The company that developed this game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_developed",
                to="games.company",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="dlcs",
            field=models.ManyToManyField(
                blank=True, help_text="DLC additions for this game.", related_name="dlc_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="expanded_games",
            field=models.ManyToManyField(
                blank=True, help_text="Games expanded by this game.", related_name="expanded_by", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="expansions",
            field=models.ManyToManyField(
                blank=True, help_text="Expansions of this game.", related_name="expansion_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="external_games",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to external platforms where this game is available.",
                related_name="games",
                to="games.externalgame",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="forks",
            field=models.ManyToManyField(
                blank=True, help_text="Fork versions derived from this game.", related_name="fork_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_engines",
            field=models.ManyToManyField(
                blank=True,
                help_text="Game engines used to build this game.",
                related_name="games",
                to="games.gameengine",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_modes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Supported game modes (single-player, multiplayer, co-op, etc.).",
                related_name="games",
                to="games.gamemode",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_status",
            field=models.ForeignKey(
                blank=True,
                help_text="The current release status of the game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.gamestatus",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The game type (Main Game, DLC, Expansion, etc.).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.gametype",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(
                help_text="Genres this game belongs to.", related_name="games", to="games.genre"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="parent_game",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent game this record is a DLC, expansion, or port of.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_games",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(
                help_text="Platforms this game is available on.", related_name="games", to="games.platform"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_perspectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="Supported player perspectives (first-person, third-person, etc.).",
                related_name="games",
                to="games.playerperspective",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="ports",
            field=models.ManyToManyField(
                blank=True, help_text="Platform ports of this game.", related_name="port_of", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="The company that published this game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_published",
                to="games.company",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(
                blank=True, help_text="The worldwide release date of the game.", null=True, verbose_name="release date"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="screenshots",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="IGDB screenshot IDs for this game.",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier, auto-generated from the English title.",
                max_length=512,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="standalone_expansions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Standalone expansions of this game.",
                related_name="standalone_expansion_of",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A short description or synopsis of the game.",
                max_length=2000,
                verbose_name="summary",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="summary_en",
            field=models.TextField(
                blank=True,
                help_text="A short description or synopsis of the game.",
                max_length=2000,
                null=True,
                verbose_name="summary",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="summary_pl",
            field=models.TextField(
                blank=True,
                help_text="A short description or synopsis of the game.",
                max_length=2000,
                null=True,
                verbose_name="summary",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(help_text="The game's title.", max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="game",
            name="title_en",
            field=models.CharField(help_text="The game's title.", max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="game",
            name="title_pl",
            field=models.CharField(help_text="The game's title.", max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="gameengine",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="gameengine",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gameengine",
            name="name",
            field=models.CharField(help_text="The game engine's name.", max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="gameengine",
            name="name_en",
            field=models.CharField(help_text="The game engine's name.", max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="gameengine",
            name="name_pl",
            field=models.CharField(help_text="The game engine's name.", max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="gamefollow",
            name="game",
            field=models.ForeignKey(
                help_text="The game being followed.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="follow_list",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamefollow",
            name="user",
            field=models.ForeignKey(
                help_text="The user following the game.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="completed_at",
            field=models.DateField(
                blank=True, help_text="The date the user completed this game.", null=True, verbose_name="completed at"
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional personal notes about this game.",
                max_length=200,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="game",
            field=models.ForeignKey(
                help_text="The game this list entry refers to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_lists",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="owned_on",
            field=models.ManyToManyField(
                help_text="The media formats on which the user owns this game.",
                related_name="game_lists",
                to="games.gamemedia",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="playtime",
            field=models.PositiveIntegerField(
                blank=True, help_text="The number of minutes played.", null=True, verbose_name="playtime"
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The user's score for this game, between 1 and 10.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="score",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="started_at",
            field=models.DateField(
                blank=True,
                help_text="The date the user started playing this game.",
                null=True,
                verbose_name="started at",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Completed"),
                    ("PTP", "Plan to play"),
                    ("P", "Playing"),
                    ("D", "Dropped"),
                    ("OH", "On hold"),
                ],
                help_text="The user's current play status (Completed, Plan to Play, Playing, Dropped, On Hold).",
                max_length=3,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="gamelist",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this game list entry.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamemedia",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="gamemedia",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="gamemedia",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="game",
            field=models.ForeignKey(
                help_text="The game being reviewed.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="review",
            field=models.TextField(blank=True, help_text="The review text.", max_length=1000, verbose_name="review"),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="user",
            field=models.ForeignKey(
                help_text="The user who wrote the review.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="average_score",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                help_text="The computed average score across all user ratings.",
                max_digits=4,
                verbose_name="average score",
            ),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="game",
            field=models.OneToOneField(
                help_text="The game this statistics record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="members_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="The number of users who have this game in their game list.",
                verbose_name="members count",
            ),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="popularity",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="The game's popularity rank, updated periodically by a background task.",
                null=True,
                verbose_name="popularity",
            ),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="rank_position",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="The game's position in the all-time ranking, updated periodically.",
                null=True,
                verbose_name="rank position",
            ),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="score_count",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of users who have scored this game.", verbose_name="score count"
            ),
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="score_sum",
            field=models.BigIntegerField(
                default=0,
                help_text="The sum of all user scores, used for average calculation.",
                verbose_name="score sum",
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="status",
            field=models.CharField(
                help_text="The release status name (e.g. Released, Alpha, Early Access).",
                max_length=255,
                unique=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="status_en",
            field=models.CharField(
                help_text="The release status name (e.g. Released, Alpha, Early Access).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="status_pl",
            field=models.CharField(
                help_text="The release status name (e.g. Released, Alpha, Early Access).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="type",
            field=models.CharField(
                help_text="The game type name (e.g. Main Game, DLC, Expansion).",
                max_length=255,
                unique=True,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="type_en",
            field=models.CharField(
                help_text="The game type name (e.g. Main Game, DLC, Expansion).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="type_pl",
            field=models.CharField(
                help_text="The game type name (e.g. Main Game, DLC, Expansion).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="A short abbreviation for the platform name (e.g. PS5, PC).",
                max_length=255,
                verbose_name="abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="playerperspective",
            name="igdb_id",
            field=models.PositiveIntegerField(
                help_text="The ID of this record in the IGDB database.", unique=True, verbose_name="igdb id"
            ),
        ),
        migrations.AlterField(
            model_name="playerperspective",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last synchronisation with IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="playerperspective",
            name="name",
            field=models.CharField(
                help_text="The display name of this record.", max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="playerperspective",
            name="name_en",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="playerperspective",
            name="name_pl",
            field=models.CharField(
                help_text="The display name of this record.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
