# Generated by Django 6.0.4 on 2026-06-18 06:32

from typing import Any

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


def backfill_search_title(apps: Any, _schema_editor: Any) -> None:
    import re
    import unicodedata

    def normalize(value: str) -> str:
        value = unicodedata.normalize("NFD", value)
        value = "".join(c for c in value if unicodedata.category(c) != "Mn")
        value = value.lower()
        value = re.sub(r"[^a-z0-9\s]", " ", value)
        return re.sub(r"\s+", " ", value).strip()

    game_model = apps.get_model("games", "Game")
    batch = []
    for game in game_model.objects.iterator(chunk_size=500):
        parts = {normalize(t) for t in (game.title_en or "", game.title_pl or "") if t}
        game.search_title = " ".join(sorted(parts))
        batch.append(game)
        if len(batch) >= 500:
            game_model.objects.bulk_update(batch, ["search_title"])
            batch.clear()
    if batch:
        game_model.objects.bulk_update(batch, ["search_title"])


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0028_alter_company_company_logo_id_alter_company_igdb_id_and_more"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name="game",
            name="search_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Normalized title used for fuzzy search (lowercase, no diacritics, no special chars).",
                max_length=511,
                verbose_name="search title",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="externalgame",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="externalgamesource",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gameengine",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AlterField(
            model_name="playerperspective",
            name="igdb_updated_at",
            field=models.DateTimeField(
                help_text="Timestamp of the last changes in IGDB.", verbose_name="igdb last updated at"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=GinIndex(
                fields=["search_title"],
                name="games_game_search_title_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.RunPython(backfill_search_title, migrations.RunPython.noop),
    ]
