from _typeshed import Incomplete

class BaseCompressor:
    def __init__(self, options: Incomplete) -> None: ...
    def compress(self, value: bytes) -> bytes: ...
    def decompress(self, value: bytes) -> bytes: ...
