@startuml entity_driagram

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

!define DICTIONARY_COLOR LightPink

legend right
    | Color | Type |
    | <#DICTIONARY_COLOR> | Dictionary class |
    | | Model class |
endlegend

entity User {
    * id : number <<generated>>
    --
    * login : text
    * password : text
    * email : text
    * nickname : text
    * date_joined : date
    * role : text <<FK>>
    * is_admin : bool
    * is_active : bool
    --
    gender : text
    avatar : image
}

entity Role #DICTIONARY_COLOR {
    * id : number <<generated>>
    --
    * name : text
}

entity FriendList {
    * id : number <<generated>>
    --
    * user : number <<FK>>
    * friends : number <<FK>>
}

entity FriendshipRequest {
    * id : number <<generated>>
    --
    * sender : number <<FK>>
    * receiver : number <<FK>>
    * message : str
    * is_active : boolean
    * created : date
}

entity Follow {
    * id : number <<generated>>
    --
    * user_id : number <<FK>>
    * game_id : number <<FK>>
    * date_of_following : date
    --
    new_review : number
}

entity StatusInList #DICTIONARY_COLOR {
    * id : number <<generated>>
    --
    * name : text
}

entity GameList {
    * id : number <<generated>>
    --
    * user_id: number <<FK>>
    * game_id : number <<FK>>
    * status_id : text <<FK>>
    * date_of_addition: date
    --
    score : number
    review : text
    date_of_adding_review : date
}

entity Publisher #DICTIONARY_COLOR {
    * id : number <<generated>>
    --
    * name : text
}

entity Game {
    * id : number <<generated>>
    --
    * title : text
    * studio_id : number <<FK>>
    * publisher_id : number <<FK>>
    * date_of_adding : date
    * is_accepted : bool
    --
    cover_image : iamge
    premiere : date
    description : text
}

entity Studio #DICTIONARY_COLOR {
    * id : number <<generated>>
    --
    * name : text
    * is_indie : bool
    * is_accepted : bool
}

entity Platform #DICTIONARY_COLOR {
    * id : number <<generated>>
    --
    * name : text
}

entity Genre #DICTIONARY_COLOR {
    * id : number <<generated>>
    --
    * name : text
}

User -- FriendList
FriendList }--{ User
User --{ FriendshipRequest
User --{ FriendshipRequest
User --{ Follow
User --{ GameList
User --{ Role
Game --{ Follow
Studio --{ Game
Publisher --{ Game
Game }--{ Platform
Game }--{ Genre
GameList -- StatusInList

@enduml

