# Generated by Django 4.0.6 on 2022-08-09 20:07

from django.db import migrations, models
import my_game_list.my_game_list.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[my_game_list.my_game_list.validators.validate_file_size], verbose_name='avatar'),
        ),
    ]
