from .. import utils as utils
from _typeshed import Incomplete

class ConfigApiMixin:
    def create_config(
        self, name: Incomplete, data: Incomplete, labels: Incomplete | None = ..., templating: Incomplete | None = ...
    ) -> Incomplete: ...
    def inspect_config(self, id: Incomplete) -> Incomplete: ...
    def remove_config(self, id: Incomplete) -> Incomplete: ...
    def configs(self, filters: Incomplete | None = ...) -> Incomplete: ...
