from .. import errors as errors, utils as utils
from _typeshed import Incomplete

class SecretApiMixin:
    def create_secret(
        self, name: Incomplete, data: Incomplete, labels: Incomplete | None = ..., driver: Incomplete | None = ...
    ) -> Incomplete: ...
    def inspect_secret(self, id: Incomplete) -> Incomplete: ...
    def remove_secret(self, id: Incomplete) -> Incomplete: ...
    def secrets(self, filters: Incomplete | None = ...) -> Incomplete: ...
