from .. import errors as errors, utils as utils
from _typeshed import Incomplete

class VolumeApiMixin:
    def volumes(self, filters: Incomplete | None = ...) -> Incomplete: ...
    def create_volume(
        self,
        name: Incomplete | None = ...,
        driver: Incomplete | None = ...,
        driver_opts: Incomplete | None = ...,
        labels: Incomplete | None = ...,
    ) -> Incomplete: ...
    def inspect_volume(self, name: Incomplete) -> Incomplete: ...
    def prune_volumes(self, filters: Incomplete | None = ...) -> Incomplete: ...
    def remove_volume(self, name: Incomplete, force: bool = ...) -> None: ...
