# Generated by Django 6.0 on 2026-01-30 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0019_alter_gameengine_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, max_length=1000, verbose_name="description")),
                ("is_favorite", models.BooleanField(default=False, verbose_name="is favorite")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUB", "Public"), ("FRI", "Friends only"), ("PRI", "Private")],
                        default="PRI",
                        max_length=3,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("S", "Solo"), ("C", "Collaborative")], default="S", max_length=1, verbose_name="mode"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaborated_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="collaborators",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(verbose_name="order")),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S Tier"),
                            ("A", "A Tier"),
                            ("B", "B Tier"),
                            ("C", "C Tier"),
                            ("D", "D Tier"),
                            ("E", "E Tier"),
                        ],
                        max_length=1,
                        verbose_name="tier",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=500, verbose_name="description")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_items_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="added by",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="collections.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_items",
                        to="games.game",
                        verbose_name="game",
                    ),
                ),
            ],
            options={
                "verbose_name": "collection item",
                "verbose_name_plural": "collection items",
                "ordering": ("id",),
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("collection", "game"), name="unique_collection_game")],
            },
        ),
    ]
