# Generated by Django 6.0 on 2026-02-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("NOR", "Normal"), ("RNK", "Ranking"), ("TIE", "Tier list")],
                default="NOR",
                max_length=3,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="order",
            field=models.PositiveIntegerField(null=True, verbose_name="order"),
        ),
    ]
