# Generated by Django 6.0 on 2026-02-11 13:26

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0003_collectionitem_unique_collection_tier_order"),
        ("games", "0019_alter_gameengine_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectionitem",
            name="unique_collection_tier_order",
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("collection", "tier", "order"),
                name="unique_collection_tier_order",
            ),
        ),
    ]
