# Generated by Django 6.0 on 2026-02-11 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0004_remove_collectionitem_unique_collection_tier_order_and_more"),
        ("games", "0019_alter_gameengine_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectionitem",
            name="unique_collection_tier_order",
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "tier", "order"), name="unique_collection_tier_order"
            ),
        ),
    ]
