# Generated by Django 6.0 on 2026-02-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0005_remove_collectionitem_unique_collection_tier_order_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectionitem",
            name="unique_collection_tier_order",
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="order",
            field=models.DecimalField(db_index=True, decimal_places=10, max_digits=20, null=True, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S Tier"),
                    ("A", "A Tier"),
                    ("B", "B Tier"),
                    ("C", "C Tier"),
                    ("D", "D Tier"),
                    ("E", "E Tier"),
                ],
                db_index=True,
                max_length=1,
                verbose_name="tier",
            ),
        ),
    ]
