# Generated by Django 6.0.3 on 2026-04-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0006_remove_collectionitem_unique_collection_tier_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, max_length=512, unique=True, verbose_name="slug"),
        ),
    ]
