# Generated by Django 6.0.4 on 2026-05-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0007_collection_slug"),
        ("games", "0028_alter_company_company_logo_id_alter_company_igdb_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users allowed to add and reorder items in COLLABORATIVE collections.",
                related_name="collaborated_collections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="collaborators",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="An optional description of the collection.",
                max_length=1000,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_favorite",
            field=models.BooleanField(
                default=False,
                help_text="Whether the collection is marked as a favourite by its owner.",
                verbose_name="is favorite",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="mode",
            field=models.CharField(
                choices=[("S", "Solo"), ("C", "Collaborative")],
                default="S",
                help_text="Collection mode: SOLO (single owner) or COLLABORATIVE (multiple contributors).",
                max_length=1,
                verbose_name="mode",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(help_text="The name of the collection.", max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier auto-generated from the owner username and collection name.",
                max_length=512,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("NOR", "Normal"), ("RNK", "Ranking"), ("TIE", "Tier list")],
                default="NOR",
                help_text="Collection type: NORMAL, RANK (ordered ranking), or TIER (tier list).",
                max_length=3,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="user",
            field=models.ForeignKey(
                help_text="The owner of the collection.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="visibility",
            field=models.CharField(
                choices=[("PUB", "Public"), ("FRI", "Friends only"), ("PRI", "Private")],
                default="PRI",
                help_text="Visibility level: PUBLIC, FRIENDS (friends only), or PRIVATE.",
                max_length=3,
                verbose_name="visibility",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="added_by",
            field=models.ForeignKey(
                help_text="The user who added this item. May be null if the adding user was deleted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_items_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="added by",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="collection",
            field=models.ForeignKey(
                help_text="The collection this item belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="collections.collection",
                verbose_name="collection",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional notes or justification for this item's position in the collection.",
                max_length=500,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="game",
            field=models.ForeignKey(
                help_text="The game this item represents.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_items",
                to="games.game",
                verbose_name="game",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="order",
            field=models.DecimalField(
                db_index=True,
                decimal_places=10,
                help_text="Fractional decimal position within the collection. Lower values appear first.",
                max_digits=20,
                null=True,
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S Tier"),
                    ("A", "A Tier"),
                    ("B", "B Tier"),
                    ("C", "C Tier"),
                    ("D", "D Tier"),
                    ("E", "E Tier"),
                ],
                db_index=True,
                help_text="Optional tier classification for TIER-type collections (S, A, B, C, D, or E).",
                max_length=1,
                verbose_name="tier",
            ),
        ),
    ]
