# Generated by Django 6.0.4 on 2026-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0008_alter_collection_collaborators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="is_favorite",
            field=models.BooleanField(
                default=False,
                help_text="Whether the collection is marked as a favorite by its owner.",
                verbose_name="is favorite",
            ),
        ),
    ]
