from _typeshed import Incomplete
from typing import ClassVar, Literal
from functools import lru_cache
from textual import events as events
from textual.app import ComposeResult as ComposeResult
from textual.screen import ModalScreen, Screen
from textual.widgets import TextArea
from textual.widgets.text_area import Location as Location

DEFAULT_IMPORT: Incomplete

@lru_cache
def get_modules() -> Incomplete: ...
@lru_cache
def get_scope() -> Incomplete: ...
@lru_cache
def import_str() -> Incomplete: ...
def run_code(code: Incomplete) -> Incomplete: ...

class ExtendedTextArea(TextArea): ...

class TextEditorBindingsInfo(ModalScreen[None]):
    BINDINGS: ClassVar[Incomplete]
    DEFAULT_CSS: ClassVar[str]
    key_bindings: str
    def compose(self) -> ComposeResult: ...

class DefaultImportsInfo(ModalScreen[None]):
    BINDINGS: ClassVar[Incomplete]
    DEFAULT_CSS: ClassVar[str]
    imported_modules: Incomplete
    def __init__(
        self, imported_modules: str, name: str | None = None, id: str | None = None, classes: str | None = None
    ) -> None: ...
    def compose(self) -> ComposeResult: ...

class InteractiveShellScreen(Screen[Incomplete]):
    input_tarea: Incomplete
    output_tarea: Incomplete
    def __init__(self, name: str | None = None, id: str | None = None, classes: str | None = None) -> None: ...
    BINDINGS: ClassVar[Incomplete]
    def compose(self) -> ComposeResult: ...
    def action_default_imports(self) -> None: ...
    def action_run_code(self) -> None: ...
    def action_copy_command(self) -> None: ...
    def action_toggle_comment(self) -> None: ...
    def action_editor_keys(self) -> None: ...
    def action_select_mode(self, mode_id: Literal["commands", "shell"]) -> None: ...
