# Generated by Django 4.0.6 on 2022-08-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamereview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game_lists",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamefollow",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="follow_list",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamefollow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="developer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="games.developer",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(related_name="games", to="games.genre"),
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(related_name="games", to="games.platform"),
        ),
        migrations.AddField(
            model_name="game",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="games.publisher",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamereview",
            constraint=models.UniqueConstraint(
                fields=("game", "user"), name="unique_game_user_in_game_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamelist",
            constraint=models.UniqueConstraint(
                fields=("game", "user"), name="unique_game_user_in_game_list"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamefollow",
            constraint=models.UniqueConstraint(
                fields=("game", "user"), name="unique_game_user_in_game_follow"
            ),
        ),
    ]
