# Generated by Django 4.1.3 on 2022-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cover_image",
            field=models.BinaryField(editable=True, max_length=307200, verbose_name="cover image"),
        ),
    ]
