# Generated by Django 5.1.1 on 2024-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_igdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
