# Generated by Django 4.0.6 on 2022-09-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, max_length=2000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="review",
            field=models.TextField(blank=True, max_length=1000, verbose_name="description"),
        ),
    ]
