# Generated by Django 4.2.4 on 2024-04-03 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamereview",
            name="score",
        ),
        migrations.AddField(
            model_name="gamelist",
            name="score",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="score",
            ),
        ),
        migrations.AlterField(
            model_name="gamereview",
            name="review",
            field=models.TextField(blank=True, max_length=1000, verbose_name="review"),
        ),
    ]
