# Generated by Django 4.2.4 on 2024-04-03 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_remove_gamereview_score_gamelist_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelist",
            name="score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="score",
            ),
        ),
    ]
