# Generated by Django 5.1.1 on 2024-09-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_published",
                to="games.company",
            ),
        ),
    ]
