# Generated by Django 4.2.4 on 2024-05-09 08:17

from django.db import migrations, models
import my_game_list.my_game_list.validators.file_size_validator


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_alter_gamelist_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cover_image",
            field=models.ImageField(
                upload_to="cover_images/",
                validators=[my_game_list.my_game_list.validators.file_size_validator.FileSizeValidator()],
                verbose_name="cover image",
            ),
        ),
    ]
