# Generated by Django 5.1.1 on 2024-09-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_alter_game_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_developed",
                to="games.company",
            ),
        ),
    ]
