# Generated by Django 5.1.1 on 2024-12-05 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_delete_developer_delete_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="igdb_checksum",
            field=models.CharField(default="123213123", max_length=255, verbose_name="igdb checksum"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="igdb_checksum",
            field=models.CharField(default="asdas", max_length=255, verbose_name="igdb checksum"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genre",
            name="igdb_checksum",
            field=models.CharField(default="123", max_length=255, verbose_name="igdb checksum"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="igdb_checksum",
            field=models.CharField(default="123", max_length=255, verbose_name="igdb checksum"),
            preserve_default=False,
        ),
    ]
