# Generated by Django 5.1.1 on 2025-01-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_gamemedia_alter_game_developer_alter_game_publisher_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamemedia",
            options={"ordering": ("id",), "verbose_name": "game_media", "verbose_name_plural": "game_medias"},
        ),
    ]
