# Generated by Django 5.1.1 on 2025-01-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_initial_values_game_media"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamemedia",
            options={"ordering": ("id",), "verbose_name": "game media", "verbose_name_plural": "game medias"},
        ),
    ]
