from _typeshed import Incomplete
from click import BaseCommand as BaseCommand, ParamType as ParamType
from dataclasses import dataclass, field
from typing import Any, Callable, Sequence

def generate_unique_id() -> Incomplete: ...
@dataclass
class MultiValueParamData:
    values: list[tuple[int | float | str]]
    @staticmethod
    def process_cli_option(value: Incomplete) -> MultiValueParamData: ...

@dataclass
class OptionSchema:
    name: list[str]
    type: ParamType
    default: MultiValueParamData | None = ...
    required: bool = ...
    is_flag: bool = ...
    is_boolean_flag: bool = ...
    flag_value: Any = ...
    opts: list[str] = field(default_factory=list)
    counting: bool = ...
    secondary_opts: list[str] = field(default_factory=list)
    key: str | tuple[str] = field(default_factory=generate_unique_id)
    help: str | None = ...
    choices: Sequence[str] | None = ...
    multiple: bool = ...
    multi_value: bool = ...
    nargs: int = ...
    def __post_init__(self) -> None: ...

@dataclass
class ArgumentSchema:
    name: str
    type: str
    required: bool = ...
    key: str = field(default_factory=generate_unique_id)
    default: MultiValueParamData | None = ...
    choices: Sequence[str] | None = ...
    multiple: bool = ...
    nargs: int = ...

@dataclass
class CommandSchema:
    name: CommandName
    function: Callable[..., Any | None]
    key: str = field(default_factory=generate_unique_id)
    docstring: str | None = ...
    options: list[OptionSchema] = field(default_factory=list)
    arguments: list[ArgumentSchema] = field(default_factory=list)
    subcommands: dict["CommandName", "CommandSchema"] = field(default_factory=dict)
    parent: CommandSchema | None = ...
    is_group: bool = ...
    @property
    def path_from_root(self) -> list["CommandSchema"]: ...

def introspect_click_app(app: Incomplete) -> dict[CommandName, CommandSchema]: ...

CommandName: Incomplete
