from .models import BlacklistedToken as BlacklistedToken, OutstandingToken as OutstandingToken
from _typeshed import Incomplete
from django.contrib import admin

class OutstandingTokenAdmin(admin.ModelAdmin[Incomplete]):
    list_display: Incomplete
    search_fields: Incomplete
    ordering: Incomplete
    def get_queryset(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    actions: Incomplete
    def get_readonly_fields(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def has_add_permission(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def has_delete_permission(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def has_change_permission(self, request: Incomplete, obj: Incomplete | None = ...) -> Incomplete: ...

class BlacklistedTokenAdmin(admin.ModelAdmin[Incomplete]):
    list_display: Incomplete
    search_fields: Incomplete
    ordering: Incomplete
    def get_queryset(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def token_jti(self, obj: Incomplete) -> Incomplete: ...
    def token_user(self, obj: Incomplete) -> Incomplete: ...
    def token_created_at(self, obj: Incomplete) -> Incomplete: ...
    def token_expires_at(self, obj: Incomplete) -> Incomplete: ...
