# Generated by Django 6.0.3 on 2026-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last active"),
        ),
    ]
