# Generated by Django 6.0.3 on 2026-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name="slug"),
        ),
    ]
