# Generated by Django 6.0.4 on 2026-05-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The user's email address. Used as the login credential.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                help_text="The user's gender. Optional.",
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the user's most recent activity. Null if never recorded.",
                null=True,
                verbose_name="last active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier for the user profile, auto-generated from the username.",
                max_length=255,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
