# Generated by Django 4.2.2 on 2023-07-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
            ],
            options={
                "verbose_name": "friendship",
                "verbose_name_plural": "friendships",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FriendshipRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(blank=True, max_length=100, verbose_name="message")),
                ("rejected_at", models.DateTimeField(blank=True, null=True, verbose_name="rejection time")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified")),
            ],
            options={
                "verbose_name": "friendship request",
                "verbose_name_plural": "friendship requests",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
