# Generated by Django 4.0.6 on 2022-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FriendList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "friend list",
                "verbose_name_plural": "friend lists",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FriendshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=100, verbose_name="message")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="The request will be inactive if the request was accepted or rejected.",
                        verbose_name="is_active",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="last modified"),
                ),
            ],
            options={
                "verbose_name": "friendship request",
                "verbose_name_plural": "friendship requests",
                "abstract": False,
            },
        ),
    ]
