# Generated by Django 4.0.6 on 2022-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The request will be inactive if the request was accepted or rejected.', verbose_name='is active'),
        ),
    ]
