# Generated by Django 6.0.4 on 2026-05-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendships", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="friend",
            field=models.ForeignKey(
                help_text="The other party in the friendship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="user",
            field=models.ForeignKey(
                help_text="One party in the friendship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendshiprequest",
            name="message",
            field=models.CharField(
                blank=True,
                help_text="An optional personal message accompanying the friendship request.",
                max_length=100,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="friendshiprequest",
            name="receiver",
            field=models.ForeignKey(
                help_text="The user who received the friendship request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendshiprequest",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the request was rejected, or null if not yet rejected.",
                null=True,
                verbose_name="rejection time",
            ),
        ),
        migrations.AlterField(
            model_name="friendshiprequest",
            name="sender",
            field=models.ForeignKey(
                help_text="The user who sent the friendship request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
