from _typeshed import Incomplete

class StoreError(RuntimeError): ...
class CredentialsNotFound(StoreError): ...
class InitializationError(StoreError): ...

def process_store_error(cpe: Incomplete, program: Incomplete) -> Incomplete: ...
