from . import constants as constants, errors as errors
from .utils import create_environment_dict as create_environment_dict
from _typeshed import Incomplete

class Store:
    program: Incomplete
    exe: Incomplete
    environment: Incomplete
    def __init__(self, program: Incomplete, environment: Incomplete | None = ...) -> None: ...
    def get(self, server: Incomplete) -> Incomplete: ...
    def store(self, server: Incomplete, username: Incomplete, secret: Incomplete) -> Incomplete: ...
    def erase(self, server: Incomplete) -> None: ...
    def list(self) -> Incomplete: ...
