from ..constants import IS_WINDOWS_PLATFORM as IS_WINDOWS_PLATFORM
from _typeshed import Incomplete

DOCKER_CONFIG_FILENAME: Incomplete
LEGACY_DOCKER_CONFIG_FILENAME: str
log: Incomplete

def find_config_file(config_path: Incomplete | None = ...) -> Incomplete: ...
def config_path_from_environment() -> Incomplete: ...
def home_dir() -> Incomplete: ...
def load_general_config(config_path: Incomplete | None = ...) -> Incomplete: ...
