from . import utils as utils
from .. import errors as errors
from _typeshed import Incomplete

def check_resource(resource_name: Incomplete) -> Incomplete: ...
def minimum_version(version: Incomplete) -> Incomplete: ...
def update_headers(f: Incomplete) -> Incomplete: ...
