from _typeshed import Incomplete

def fnmatch(name: Incomplete, pat: Incomplete) -> Incomplete: ...
def fnmatchcase(name: Incomplete, pat: Incomplete) -> Incomplete: ...
def translate(pat: Incomplete) -> Incomplete: ...
