from ..errors import StreamParseError as StreamParseError
from _typeshed import Incomplete
from collections.abc import Generator

json_decoder: Incomplete

def stream_as_text(stream: Incomplete) -> Generator[Incomplete, None, None]: ...
def json_splitter(buffer: Incomplete) -> Incomplete: ...
def json_stream(stream: Incomplete) -> Incomplete: ...
def line_splitter(buffer: Incomplete, separator: str = ...) -> Incomplete: ...
def split_buffer(
    stream: Incomplete, splitter: Incomplete | None = ..., decoder: Incomplete = ...
) -> Generator[Incomplete, None, Incomplete]: ...
