from .utils import format_environment as format_environment
from _typeshed import Incomplete

class ProxyConfig(dict[Incomplete, Incomplete]):
    @property
    def http(self) -> Incomplete: ...
    @property
    def https(self) -> Incomplete: ...
    @property
    def ftp(self) -> Incomplete: ...
    @property
    def no_proxy(self) -> Incomplete: ...
    @staticmethod
    def from_dict(config: Incomplete) -> Incomplete: ...
    def get_environment(self) -> Incomplete: ...
    def inject_proxy_environment(self, environment: Incomplete) -> Incomplete: ...
