from ..api import APIClient as APIClient
from ..constants import DEFAULT_DATA_CHUNK_SIZE as DEFAULT_DATA_CHUNK_SIZE
from ..errors import (
    ContainerError as ContainerError,
    DockerException as DockerException,
    ImageNotFound as ImageNotFound,
    NotFound as NotFound,
    create_unexpected_kwargs_error as create_unexpected_kwargs_error,
)
from ..types import HostConfig as HostConfig
from ..utils import version_gte as version_gte
from .images import Image as Image
from .resource import Collection as Collection, Model as Model
from _typeshed import Incomplete
from typing import NamedTuple

class Container(Model):
    @property
    def name(self) -> Incomplete: ...
    @property
    def image(self) -> Incomplete: ...
    @property
    def labels(self) -> Incomplete: ...
    @property
    def status(self) -> Incomplete: ...
    @property
    def ports(self) -> Incomplete: ...
    def attach(self, **kwargs: Incomplete) -> Incomplete: ...
    def attach_socket(self, **kwargs: Incomplete) -> Incomplete: ...
    def commit(
        self, repository: Incomplete | None = ..., tag: Incomplete | None = ..., **kwargs: Incomplete
    ) -> Incomplete: ...
    def diff(self) -> Incomplete: ...
    def exec_run(
        self,
        cmd: Incomplete,
        stdout: bool = ...,
        stderr: bool = ...,
        stdin: bool = ...,
        tty: bool = ...,
        privileged: bool = ...,
        user: str = ...,
        detach: bool = ...,
        stream: bool = ...,
        socket: bool = ...,
        environment: Incomplete | None = ...,
        workdir: Incomplete | None = ...,
        demux: bool = ...,
    ) -> Incomplete: ...
    def export(self, chunk_size: Incomplete = ...) -> Incomplete: ...
    def get_archive(self, path: Incomplete, chunk_size: Incomplete = ..., encode_stream: bool = ...) -> Incomplete: ...
    def kill(self, signal: Incomplete | None = ...) -> Incomplete: ...
    def logs(self, **kwargs: Incomplete) -> Incomplete: ...
    def pause(self) -> Incomplete: ...
    def put_archive(self, path: Incomplete, data: Incomplete) -> Incomplete: ...
    def remove(self, **kwargs: Incomplete) -> Incomplete: ...
    def rename(self, name: Incomplete) -> Incomplete: ...
    def resize(self, height: Incomplete, width: Incomplete) -> Incomplete: ...
    def restart(self, **kwargs: Incomplete) -> Incomplete: ...
    def start(self, **kwargs: Incomplete) -> Incomplete: ...
    def stats(self, **kwargs: Incomplete) -> Incomplete: ...
    def stop(self, **kwargs: Incomplete) -> Incomplete: ...
    def top(self, **kwargs: Incomplete) -> Incomplete: ...
    def unpause(self) -> Incomplete: ...
    def update(self, **kwargs: Incomplete) -> Incomplete: ...
    def wait(self, **kwargs: Incomplete) -> Incomplete: ...

class ContainerCollection(Collection):
    model = Container
    def run(
        self,
        image: Incomplete,
        command: Incomplete | None = ...,
        stdout: bool = ...,
        stderr: bool = ...,
        remove: bool = ...,
        **kwargs: Incomplete
    ) -> Incomplete: ...
    def create(self, image: Incomplete, command: Incomplete | None = ..., **kwargs: Incomplete) -> Incomplete: ...  # type: ignore[override]
    def get(self, container_id: Incomplete) -> Incomplete: ...
    def list(
        self,
        all: bool = ...,
        before: Incomplete | None = ...,
        filters: Incomplete | None = ...,
        limit: int = ...,
        since: Incomplete | None = ...,
        sparse: bool = ...,
        ignore_removed: bool = ...,
    ) -> Incomplete: ...
    def prune(self, filters: Incomplete | None = ...) -> Incomplete: ...

RUN_CREATE_KWARGS: Incomplete
RUN_HOST_CONFIG_KWARGS: Incomplete

class ExecResult(NamedTuple):
    exit_code: Incomplete
    output: Incomplete
