from .resource import Collection as Collection, Model as Model
from _typeshed import Incomplete

class Node(Model):
    id_attribute: str
    @property
    def version(self) -> Incomplete: ...
    def update(self, node_spec: Incomplete) -> Incomplete: ...
    def remove(self, force: bool = ...) -> Incomplete: ...

class NodeCollection(Collection):
    model = Node
    def get(self, node_id: Incomplete) -> Incomplete: ...
    def list(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
