from _typeshed import Incomplete

class Model:
    id_attribute: str
    client: Incomplete
    collection: Incomplete
    attrs: Incomplete
    def __init__(
        self, attrs: Incomplete | None = ..., client: Incomplete | None = ..., collection: Incomplete | None = ...
    ) -> None: ...
    def __eq__(self, other: Incomplete) -> Incomplete: ...
    def __hash__(self) -> Incomplete: ...
    @property
    def id(self) -> Incomplete: ...
    @property
    def short_id(self) -> Incomplete: ...
    def reload(self) -> None: ...

class Collection:
    model: Incomplete
    client: Incomplete
    def __init__(self, client: Incomplete | None = ...) -> None: ...
    def __call__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def list(self) -> None: ...
    def get(self, key: Incomplete) -> None: ...
    def create(self, attrs: Incomplete | None = ...) -> None: ...
    def prepare_model(self, attrs: Incomplete) -> Incomplete: ...
